// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "debtomate/module/entities"

	mock "github.com/stretchr/testify/mock"
)

// AuthRepositoryInterface is an autogenerated mock type for the AuthRepositoryInterface type
type AuthRepositoryInterface struct {
	mock.Mock
}

// GetUsersByEmail provides a mock function with given fields: email
func (_m *AuthRepositoryInterface) GetUsersByEmail(email string) (*entities.AdminModels, error) {
	ret := _m.Called(email)

	var r0 *entities.AdminModels
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.AdminModels, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.AdminModels); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AdminModels)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthRepositoryInterface creates a new instance of AuthRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepositoryInterface {
	mock := &AuthRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
