// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "ruti-store/module/entities"

	mock "github.com/stretchr/testify/mock"
)

// AuthRepositoryInterface is an autogenerated mock type for the AuthRepositoryInterface type
type AuthRepositoryInterface struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: req
func (_m *AuthRepositoryInterface) CreateUser(req *entities.UserModels) (*entities.UserModels, error) {
	ret := _m.Called(req)

	var r0 *entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.UserModels) (*entities.UserModels, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*entities.UserModels) *entities.UserModels); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.UserModels) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersByEmail provides a mock function with given fields: email
func (_m *AuthRepositoryInterface) GetUsersByEmail(email string) (*entities.UserModels, error) {
	ret := _m.Called(email)

	var r0 *entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.UserModels, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.UserModels); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthRepositoryInterface creates a new instance of AuthRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepositoryInterface {
	mock := &AuthRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
