// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "ruti-store/module/entities"
	domain "ruti-store/module/feature/address/domain"

	mock "github.com/stretchr/testify/mock"
)

// AddressServiceInterface is an autogenerated mock type for the AddressServiceInterface type
type AddressServiceInterface struct {
	mock.Mock
}

// CreateAddress provides a mock function with given fields: userID, req
func (_m *AddressServiceInterface) CreateAddress(userID uint64, req *domain.CreateAddressRequest) (*entities.AddressModels, error) {
	ret := _m.Called(userID, req)

	var r0 *entities.AddressModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, *domain.CreateAddressRequest) (*entities.AddressModels, error)); ok {
		return rf(userID, req)
	}
	if rf, ok := ret.Get(0).(func(uint64, *domain.CreateAddressRequest) *entities.AddressModels); ok {
		r0 = rf(userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, *domain.CreateAddressRequest) error); ok {
		r1 = rf(userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAddress provides a mock function with given fields: addressID, userID
func (_m *AddressServiceInterface) DeleteAddress(addressID uint64, userID uint64) error {
	ret := _m.Called(addressID, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = rf(addressID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAddressByID provides a mock function with given fields: addressID
func (_m *AddressServiceInterface) GetAddressByID(addressID uint64) (*entities.AddressModels, error) {
	ret := _m.Called(addressID)

	var r0 *entities.AddressModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*entities.AddressModels, error)); ok {
		return rf(addressID)
	}
	if rf, ok := ret.Get(0).(func(uint64) *entities.AddressModels); ok {
		r0 = rf(addressID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(addressID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAddressesPage provides a mock function with given fields: userID, currentPage, pageSize
func (_m *AddressServiceInterface) GetAddressesPage(userID uint64, currentPage int, pageSize int) (int, int, int, int, error) {
	ret := _m.Called(userID, currentPage, pageSize)

	var r0 int
	var r1 int
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(uint64, int, int) (int, int, int, int, error)); ok {
		return rf(userID, currentPage, pageSize)
	}
	if rf, ok := ret.Get(0).(func(uint64, int, int) int); ok {
		r0 = rf(userID, currentPage, pageSize)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(uint64, int, int) int); ok {
		r1 = rf(userID, currentPage, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(uint64, int, int) int); ok {
		r2 = rf(userID, currentPage, pageSize)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(uint64, int, int) int); ok {
		r3 = rf(userID, currentPage, pageSize)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(uint64, int, int) error); ok {
		r4 = rf(userID, currentPage, pageSize)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// GetAllAddresses provides a mock function with given fields: userID, page, pageSize
func (_m *AddressServiceInterface) GetAllAddresses(userID uint64, page int, pageSize int) ([]*entities.AddressModels, int64, error) {
	ret := _m.Called(userID, page, pageSize)

	var r0 []*entities.AddressModels
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint64, int, int) ([]*entities.AddressModels, int64, error)); ok {
		return rf(userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(uint64, int, int) []*entities.AddressModels); ok {
		r0 = rf(userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, int, int) int64); ok {
		r1 = rf(userID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint64, int, int) error); ok {
		r2 = rf(userID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetCity provides a mock function with given fields: province
func (_m *AddressServiceInterface) GetCity(province string) (map[string]interface{}, error) {
	ret := _m.Called(province)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]interface{}, error)); ok {
		return rf(province)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(province)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(province)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProvince provides a mock function with given fields:
func (_m *AddressServiceInterface) GetProvince() (map[string]interface{}, error) {
	ret := _m.Called()

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]interface{}, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAddress provides a mock function with given fields: addressID, req
func (_m *AddressServiceInterface) UpdateAddress(addressID uint64, req *domain.UpdateAddressRequest) (*entities.AddressModels, error) {
	ret := _m.Called(addressID, req)

	var r0 *entities.AddressModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, *domain.UpdateAddressRequest) (*entities.AddressModels, error)); ok {
		return rf(addressID, req)
	}
	if rf, ok := ret.Get(0).(func(uint64, *domain.UpdateAddressRequest) *entities.AddressModels); ok {
		r0 = rf(addressID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, *domain.UpdateAddressRequest) error); ok {
		r1 = rf(addressID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAddressServiceInterface creates a new instance of AddressServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressServiceInterface {
	mock := &AddressServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
