// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "ruti-store/module/entities"

	mock "github.com/stretchr/testify/mock"
)

// AddressRepositoryInterface is an autogenerated mock type for the AddressRepositoryInterface type
type AddressRepositoryInterface struct {
	mock.Mock
}

// CreateAddress provides a mock function with given fields: newData
func (_m *AddressRepositoryInterface) CreateAddress(newData *entities.AddressModels) (*entities.AddressModels, error) {
	ret := _m.Called(newData)

	var r0 *entities.AddressModels
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.AddressModels) (*entities.AddressModels, error)); ok {
		return rf(newData)
	}
	if rf, ok := ret.Get(0).(func(*entities.AddressModels) *entities.AddressModels); ok {
		r0 = rf(newData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.AddressModels) error); ok {
		r1 = rf(newData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAddress provides a mock function with given fields: addressID
func (_m *AddressRepositoryInterface) DeleteAddress(addressID uint64) error {
	ret := _m.Called(addressID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(addressID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAddressByID provides a mock function with given fields: addressID
func (_m *AddressRepositoryInterface) GetAddressByID(addressID uint64) (*entities.AddressModels, error) {
	ret := _m.Called(addressID)

	var r0 *entities.AddressModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*entities.AddressModels, error)); ok {
		return rf(addressID)
	}
	if rf, ok := ret.Get(0).(func(uint64) *entities.AddressModels); ok {
		r0 = rf(addressID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(addressID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCity provides a mock function with given fields: province
func (_m *AddressRepositoryInterface) GetCity(province string) (map[string]interface{}, error) {
	ret := _m.Called(province)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]interface{}, error)); ok {
		return rf(province)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(province)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(province)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginatedAddresses provides a mock function with given fields: userID, page, pageSize
func (_m *AddressRepositoryInterface) GetPaginatedAddresses(userID uint64, page int, pageSize int) ([]*entities.AddressModels, error) {
	ret := _m.Called(userID, page, pageSize)

	var r0 []*entities.AddressModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, int, int) ([]*entities.AddressModels, error)); ok {
		return rf(userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(uint64, int, int) []*entities.AddressModels); ok {
		r0 = rf(userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, int, int) error); ok {
		r1 = rf(userID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPrimaryAddressByUserID provides a mock function with given fields: userID
func (_m *AddressRepositoryInterface) GetPrimaryAddressByUserID(userID uint64) (*entities.AddressModels, error) {
	ret := _m.Called(userID)

	var r0 *entities.AddressModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*entities.AddressModels, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) *entities.AddressModels); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProvince provides a mock function with given fields:
func (_m *AddressRepositoryInterface) GetProvince() (map[string]interface{}, error) {
	ret := _m.Called()

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]interface{}, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalItems provides a mock function with given fields: userID
func (_m *AddressRepositoryInterface) GetTotalItems(userID uint64) (int64, error) {
	ret := _m.Called(userID)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (int64, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) int64); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAddress provides a mock function with given fields: addressID, updatedAddress
func (_m *AddressRepositoryInterface) UpdateAddress(addressID uint64, updatedAddress *entities.AddressModels) (*entities.AddressModels, error) {
	ret := _m.Called(addressID, updatedAddress)

	var r0 *entities.AddressModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, *entities.AddressModels) (*entities.AddressModels, error)); ok {
		return rf(addressID, updatedAddress)
	}
	if rf, ok := ret.Get(0).(func(uint64, *entities.AddressModels) *entities.AddressModels); ok {
		r0 = rf(addressID, updatedAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, *entities.AddressModels) error); ok {
		r1 = rf(addressID, updatedAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateIsPrimary provides a mock function with given fields: addressID, isPrimary
func (_m *AddressRepositoryInterface) UpdateIsPrimary(addressID uint64, isPrimary bool) error {
	ret := _m.Called(addressID, isPrimary)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, bool) error); ok {
		r0 = rf(addressID, isPrimary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAddressRepositoryInterface creates a new instance of AddressRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressRepositoryInterface {
	mock := &AddressRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
